[project]
name = "sec-form4"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "llm>=0.27.1",
    "pandas>=2.3.1",
    "requests>=2.32.5",
    "sec-edgar-downloader>=5.0.3",
    "yfinance>=0.2.65",
]
